import { Head, Html, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang='pt-Br'>
      <Head>
        <title>Teste front-end tinnova</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
