import Head from 'next/head'
import { Inter as Manrope } from 'next/font/google'
import { useState } from 'react'
import { FormCreateOrAlterUser } from '~features'

const manrope = Manrope({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600'],
})

export default function Home() {
  const [isCreate, setIsCreate] = useState(false)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={manrope.className}>
        <div
          style={{
            minHeight: '100vh',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: '#fafafa',
            padding: '1.5rem',
          }}
        >
          <div
            style={{
              alignItems: 'center',
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'center',
              gap: '0.75rem',
              padding: '0.75rem',
              maxWidth: '47.75rem',
              width: '100%',
              border: '1px solid #f0f0f0',
              borderRadius: '8px',
              boxShadow:
                '0 1px 2px 0 rgba(0, 0, 0, 0.03), 0 1px 6px -1px rgba(0, 0, 0, 0.02), 0 2px 4px 0 rgba(0, 0, 0, 0.02)',
            }}
          >
            <p style={{ fontWeight: 600, width: ' 100%' }}>
              Teste front-end tinnova
            </p>
            <div
              style={{
                alignItems: 'center',
                display: 'flex',
                gap: '0.5rem',
                width: '100%',
              }}
            >
              <button onClick={() => setIsCreate(false)}>
                Tabela de usuários
              </button>
              <button onClick={() => setIsCreate(true)}>
                Cadastro de usuários
              </button>
            </div>
            <div
              style={{
                width: '100%',
                flex: 1,
              }}
            >
              {isCreate ? (
                <FormCreateOrAlterUser />
              ) : (
                <table
                  style={{
                    borderCollapse: 'collapse',
                    tableLayout: 'fixed',
                    width: '100%',
                  }}
                >
                  <thead>
                    <tr>
                      <th>Nome</th>
                      <th>CPF</th>
                      <th>Telefone</th>
                      <th>E-mail</th>
                      <th>Ações</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td align='center'>sd asdasd asdaasda dasdas</td>
                      <td align='center'>231423423</td>
                      <td align='center'>1231234234</td>
                      <td align='center'>asdsd@dasdas.com</td>
                      <td align='center'>asdsd@dasdas.com</td>
                    </tr>
                  </tbody>
                </table>
              )}
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
